// location
export const GET_COUNTRIES_LIST = 'GET_COUNTRIES_LIST';
export const GET_COUNTRIES_LIST_SUCCESS = 'GET_COUNTRIES_LIST_SUCCESS';
export const GET_ALL_CITIES_LIST = 'GET_ALL_CITIES_LIST';
export const GET_ALL_CITIES_LIST_SUCCESS = 'GET_ALL_CITIES_LIST_SUCCESS';
export const GET_SELECTED_CITIES_LIST = 'GET_SELECTED_CITIES_LIST';
export const GET_SELECTED_CITIES_LIST_SUCCESS = 'GET_SELECTED_CITIES_LIST_SUCCESS';
// vendor
export const ADD_VENDOR = 'ADD_VENDOR';
export const DELETE_VENDOR = 'DELETE_VENDOR';
