// location
export const GET_LOCATIONS_LIST = 'GET_LOCATIONS_LIST';
export const GET_LOCATIONS_LIST_SUCCESS = 'GET_LOCATIONS_LIST_SUCCESS';
export const GET_LOCATIONS_LIST_FAILURE = 'GET_LOCATIONS_LIST_FAILURE';
export const GET_LOCATION_BY_ID = 'GET_LOCATION_BY_ID';
export const GET_LOCATION_BY_ID_SUCCESS = 'GET_LOCATION_BY_ID_SUCCESS';
export const GET_LOCATION_BY_ID_FAILURE = 'GET_LOCATION_BY_ID_FAILURE';
// vendor
export const GET_VENDORS = 'GET_VENDORS';
export const GET_VENDORS_SUCCESS = 'GET_VENDORS_SUCCESS';
export const GET_VENDORS_FAILURE = 'GET_VENDORS_FAILURE';
export const ADD_VENDOR = 'ADD_VENDOR';
export const ADD_VENDOR_SUCCESS = 'ADD_VENDOR_SUCCESS';
export const ADD_VENDOR_FAILURE = 'ADD_VENDOR_FAILURE';
export const ADD_VENDOR_CLEAR_STATUS = 'ADD_VENDOR_CLEAR_STATUS';
export const DELETE_VENDOR = 'DELETE_VENDOR';
export const DELETE_VENDOR_SUCCESS = 'DELETE_VENDOR_SUCCESS';
export const DELETE_VENDOR_FAILURE = 'DELETE_VENDOR_FAILURE';
export const DELETE_VENDOR_CLEAR_STATUS = 'DELETE_VENDOR_CLEAR_STATUS';
export const UPDATE_VENDOR_SUCCESS = 'UPDATE_VENDOR_SUCCESS';
